/**
 * Brazilian states and cities data
 * Used for autocomplete in signup and settings
 */

export interface BrazilianState {
  uf: string;
  name: string;
}

export const BRAZILIAN_STATES: BrazilianState[] = [
  { uf: 'AC', name: 'Acre' },
  { uf: 'AL', name: 'Alagoas' },
  { uf: 'AP', name: 'Amapá' },
  { uf: 'AM', name: 'Amazonas' },
  { uf: 'BA', name: 'Bahia' },
  { uf: 'CE', name: 'Ceará' },
  { uf: 'DF', name: 'Distrito Federal' },
  { uf: 'ES', name: 'Espírito Santo' },
  { uf: 'GO', name: 'Goiás' },
  { uf: 'MA', name: 'Maranhão' },
  { uf: 'MT', name: 'Mato Grosso' },
  { uf: 'MS', name: 'Mato Grosso do Sul' },
  { uf: 'MG', name: 'Minas Gerais' },
  { uf: 'PA', name: 'Pará' },
  { uf: 'PB', name: 'Paraíba' },
  { uf: 'PR', name: 'Paraná' },
  { uf: 'PE', name: 'Pernambuco' },
  { uf: 'PI', name: 'Piauí' },
  { uf: 'RJ', name: 'Rio de Janeiro' },
  { uf: 'RN', name: 'Rio Grande do Norte' },
  { uf: 'RS', name: 'Rio Grande do Sul' },
  { uf: 'RO', name: 'Rondônia' },
  { uf: 'RR', name: 'Roraima' },
  { uf: 'SC', name: 'Santa Catarina' },
  { uf: 'SP', name: 'São Paulo' },
  { uf: 'SE', name: 'Sergipe' },
  { uf: 'TO', name: 'Tocantins' },
];

/**
 * Cities by state (UF)
 * Sample of major cities for each state
 */
export const CITIES_BY_UF: Record<string, string[]> = {
  SP: [
    'São Paulo',
    'Campinas',
    'Santos',
    'Ribeirão Preto',
    'São José dos Campos',
    'Sorocaba',
    'São Bernardo do Campo',
    'Santo André',
    'Osasco',
    'Guarulhos',
    'Mogi das Cruzes',
    'Bauru',
    'Piracicaba',
    'Jundiaí',
    'São José do Rio Preto',
  ],
  RJ: [
    'Rio de Janeiro',
    'Niterói',
    'São Gonçalo',
    'Duque de Caxias',
    'Nova Iguaçu',
    'Belford Roxo',
    'São João de Meriti',
    'Campos dos Goytacazes',
    'Petrópolis',
    'Volta Redonda',
    'Magé',
    'Itaboraí',
    'Macaé',
    'Cabo Frio',
    'Angra dos Reis',
  ],
  MG: [
    'Belo Horizonte',
    'Uberlândia',
    'Contagem',
    'Juiz de Fora',
    'Betim',
    'Montes Claros',
    'Ribeirão das Neves',
    'Uberaba',
    'Governador Valadares',
    'Ipatinga',
    'Santa Luzia',
    'Sete Lagoas',
    'Divinópolis',
    'Poços de Caldas',
    'Patos de Minas',
  ],
  RS: [
    'Porto Alegre',
    'Caxias do Sul',
    'Pelotas',
    'Canoas',
    'Santa Maria',
    'Gravataí',
    'Viamão',
    'Novo Hamburgo',
    'São Leopoldo',
    'Rio Grande',
    'Alvorada',
    'Passo Fundo',
    'Sapucaia do Sul',
    'Uruguaiana',
    'Santa Cruz do Sul',
  ],
  PR: [
    'Curitiba',
    'Londrina',
    'Maringá',
    'Ponta Grossa',
    'Cascavel',
    'São José dos Pinhais',
    'Foz do Iguaçu',
    'Colombo',
    'Guarapuava',
    'Paranaguá',
    'Araucária',
    'Toledo',
    'Apucarana',
    'Pinhais',
    'Campo Largo',
  ],
  BA: [
    'Salvador',
    'Feira de Santana',
    'Vitória da Conquista',
    'Camaçari',
    'Itabuna',
    'Juazeiro',
    'Lauro de Freitas',
    'Ilhéus',
    'Jequié',
    'Teixeira de Freitas',
    'Alagoinhas',
    'Barreiras',
    'Porto Seguro',
    'Simões Filho',
    'Paulo Afonso',
  ],
  SC: [
    'Florianópolis',
    'Joinville',
    'Blumenau',
    'São José',
    'Criciúma',
    'Chapecó',
    'Itajaí',
    'Jaraguá do Sul',
    'Lages',
    'Palhoça',
    'Balneário Camboriú',
    'Brusque',
    'Tubarão',
    'São Bento do Sul',
    'Caçador',
  ],
  PE: [
    'Recife',
    'Jaboatão dos Guararapes',
    'Olinda',
    'Paulista',
    'Caruaru',
    'Petrolina',
    'Cabo de Santo Agostinho',
    'Camaragibe',
    'Garanhuns',
    'Vitória de Santo Antão',
    'Igarassu',
    'São Lourenço da Mata',
    'Abreu e Lima',
    'Santa Cruz do Capibaribe',
    'Ipojuca',
  ],
  CE: [
    'Fortaleza',
    'Caucaia',
    'Juazeiro do Norte',
    'Maracanaú',
    'Sobral',
    'Crato',
    'Itapipoca',
    'Maranguape',
    'Iguatu',
    'Quixadá',
    'Canindé',
    'Pacajus',
    'Aquiraz',
    'Quixeramobim',
    'Cascavel',
  ],
  GO: [
    'Goiânia',
    'Aparecida de Goiânia',
    'Anápolis',
    'Rio Verde',
    'Luziânia',
    'Águas Lindas de Goiás',
    'Valparaíso de Goiás',
    'Trindade',
    'Formosa',
    'Novo Gama',
    'Itumbiara',
    'Senador Canedo',
    'Catalão',
    'Jataí',
    'Planaltina',
  ],
  PA: [
    'Belém',
    'Ananindeua',
    'Santarém',
    'Marabá',
    'Castanhal',
    'Parauapebas',
    'Itaituba',
    'Cametá',
    'Bragança',
    'Abaetetuba',
    'Marituba',
    'Altamira',
    'Tucuruí',
    'Paragominas',
    'Redenção',
  ],
  AM: [
    'Manaus',
    'Parintins',
    'Itacoatiara',
    'Manacapuru',
    'Coari',
    'Tefé',
    'Tabatinga',
    'Maués',
    'Humaitá',
    'Iranduba',
    'São Gabriel da Cachoeira',
    'Lábrea',
    'Eirunepé',
    'Manicoré',
    'Presidente Figueiredo',
  ],
  MA: [
    'São Luís',
    'Imperatriz',
    'São José de Ribamar',
    'Timon',
    'Caxias',
    'Codó',
    'Paço do Lumiar',
    'Açailândia',
    'Bacabal',
    'Balsas',
    'Santa Inês',
    'Pinheiro',
    'Pedreiras',
    'Chapadinha',
    'Barra do Corda',
  ],
  DF: [
    'Brasília',
    'Ceilândia',
    'Taguatinga',
    'Samambaia',
    'Planaltina',
    'Águas Claras',
    'Gama',
    'Santa Maria',
    'São Sebastião',
    'Recanto das Emas',
    'Sobradinho',
    'Brazlândia',
    'Paranoá',
    'Riacho Fundo',
    'Guará',
  ],
  ES: [
    'Vitória',
    'Vila Velha',
    'Serra',
    'Cariacica',
    'Cachoeiro de Itapemirim',
    'Linhares',
    'São Mateus',
    'Colatina',
    'Guarapari',
    'Aracruz',
    'Viana',
    'Nova Venécia',
    'Barra de São Francisco',
    'Marataízes',
    'São Gabriel da Palha',
  ],
  MT: [
    'Cuiabá',
    'Várzea Grande',
    'Rondonópolis',
    'Sinop',
    'Tangará da Serra',
    'Cáceres',
    'Sorriso',
    'Lucas do Rio Verde',
    'Barra do Garças',
    'Primavera do Leste',
    'Alta Floresta',
    'Peixoto de Azevedo',
    'Pontes e Lacerda',
    'Juína',
    'Colíder',
  ],
  MS: [
    'Campo Grande',
    'Dourados',
    'Três Lagoas',
    'Corumbá',
    'Ponta Porã',
    'Sidrolândia',
    'Naviraí',
    'Nova Andradina',
    'Aquidauana',
    'Paranaíba',
    'Maracaju',
    'Coxim',
    'Amambai',
    'Rio Brilhante',
    'Chapadão do Sul',
  ],
  RN: [
    'Natal',
    'Mossoró',
    'Parnamirim',
    'São Gonçalo do Amarante',
    'Macaíba',
    'Ceará-Mirim',
    'Caicó',
    'Assu',
    'Currais Novos',
    'São José de Mipibu',
    'Nova Cruz',
    'Pau dos Ferros',
    'Santa Cruz',
    'Extremoz',
    'Touros',
  ],
  PB: [
    'João Pessoa',
    'Campina Grande',
    'Santa Rita',
    'Patos',
    'Bayeux',
    'Sousa',
    'Cajazeiras',
    'Cabedelo',
    'Guarabira',
    'Mamanguape',
    'Rio Tinto',
    'Monteiro',
    'Pombal',
    'Sapé',
    'Itabaiana',
  ],
  AL: [
    'Maceió',
    'Arapiraca',
    'Rio Largo',
    'Palmeira dos Índios',
    'União dos Palmares',
    'Penedo',
    'São Miguel dos Campos',
    'Santana do Ipanema',
    'Delmiro Gouveia',
    'Coruripe',
    'Marechal Deodoro',
    'Arapiraca',
    'Campo Alegre',
    'Pilar',
    'Murici',
  ],
  SE: [
    'Aracaju',
    'Nossa Senhora do Socorro',
    'Lagarto',
    'Itabaiana',
    'São Cristóvão',
    'Estância',
    'Tobias Barreto',
    'Simão Dias',
    'Propriá',
    'Barra dos Coqueiros',
    'Laranjeiras',
    'Itabaianinha',
    'Ribeirópolis',
    'Umbaúba',
    'Japaratuba',
  ],
  PI: [
    'Teresina',
    'Parnaíba',
    'Picos',
    'Piripiri',
    'Floriano',
    'Campo Maior',
    'Barras',
    'União',
    'Altos',
    'Esperantina',
    'Pedro II',
    'Valença do Piauí',
    'São Raimundo Nonato',
    'Oeiras',
    'Batalha',
  ],
  TO: [
    'Palmas',
    'Araguaína',
    'Gurupi',
    'Porto Nacional',
    'Paraíso do Tocantins',
    'Araguatins',
    'Colinas do Tocantins',
    'Guaraí',
    'Tocantinópolis',
    'Miracema do Tocantins',
    'Formoso do Araguaia',
    'Dianópolis',
    'Pedro Afonso',
    'Augustinópolis',
    'Taguatinga',
  ],
  RO: [
    'Porto Velho',
    'Ji-Paraná',
    'Ariquemes',
    'Vilhena',
    'Cacoal',
    'Jaru',
    'Rolim de Moura',
    'Pimenta Bueno',
    'Guajará-Mirim',
    'Buritis',
    'São Miguel do Guaporé',
    'Ouro Preto do Oeste',
    'Presidente Médici',
    'Espigão do Oeste',
    'Colorado do Oeste',
  ],
  RR: [
    'Boa Vista',
    'Rorainópolis',
    'Caracaraí',
    'Alto Alegre',
    'Mucajaí',
    'Bonfim',
    'Cantá',
    'São João da Baliza',
    'São Luiz',
    'Caroebe',
    'Normandia',
    'Pacaraima',
    'Amajari',
    'Iracema',
    'Uiramutã',
  ],
  AC: [
    'Rio Branco',
    'Cruzeiro do Sul',
    'Sena Madureira',
    'Tarauacá',
    'Feijó',
    'Brasiléia',
    'Plácido de Castro',
    'Senador Guiomard',
    'Epitaciolândia',
    'Xapuri',
    'Mâncio Lima',
    'Bujari',
    'Acrelândia',
    'Rodrigues Alves',
    'Capixaba',
  ],
  AP: [
    'Macapá',
    'Santana',
    'Laranjal do Jari',
    'Oiapoque',
    'Mazagão',
    'Porto Grande',
    'Tartarugalzinho',
    'Pedra Branca do Amapari',
    'Vitória do Jari',
    'Calçoene',
    'Amapá',
    'Ferreira Gomes',
    'Serra do Navio',
    'Pracuúba',
    'Itaubal',
  ],
};

/**
 * Search states by name or UF (case-insensitive)
 */
export function searchStates(query: string): BrazilianState[] {
  if (!query) return BRAZILIAN_STATES;
  
  const lowerQuery = query.toLowerCase();
  
  return BRAZILIAN_STATES.filter(state => 
    state.name.toLowerCase().includes(lowerQuery) ||
    state.uf.toLowerCase().includes(lowerQuery)
  );
}

/**
 * Get cities for a specific UF
 */
export function getCitiesForState(uf: string): string[] {
  return CITIES_BY_UF[uf.toUpperCase()] || [];
}

/**
 * Search cities within a state (case-insensitive)
 */
export function searchCities(uf: string, query: string): string[] {
  const cities = getCitiesForState(uf);
  
  if (!query) return cities;
  
  const lowerQuery = query.toLowerCase();
  
  return cities.filter(city => 
    city.toLowerCase().includes(lowerQuery)
  );
}

/**
 * Get state object by UF
 */
export function getStateByUF(uf: string): BrazilianState | undefined {
  return BRAZILIAN_STATES.find(state => state.uf.toUpperCase() === uf.toUpperCase());
}
