import type { ReactNode } from 'react';
import type { AssistantAutomation,AssistantAutomationExecution } from '../../types/assistant';
export function AutomationStatusBadge({status}:{status:string}){const tone=status==='paused'?'bg-amber-100 text-amber-700':status==='blocked'||status==='failed'?'bg-red-100 text-red-700':'bg-indigo-100 text-indigo-700';return <span className={`rounded px-2 py-0.5 text-[11px] ${tone}`}>{status}</span>}
export function AutomationScheduleCard({automation}:{automation:AssistantAutomation}){return <div className="mt-2 text-xs"><b>Frequência:</b> {automation.schedule?.mode||'manual'} {automation.schedule?.time?`às ${automation.schedule.time}`:''}<br/><b>Timezone:</b> {automation.timezone}<br/><b>Próxima execução:</b> {automation.nextExecutionAt?new Date(automation.nextExecutionAt).toLocaleString('pt-BR'):'somente manual'}</div>}
export function AutomationConditionCard({automation}:{automation:AssistantAutomation}){return automation.condition?<div className="mt-2 rounded bg-slate-50 p-2 text-xs"><b>Condição:</b> {automation.condition.source}.{automation.condition.conditionType} {automation.condition.operator} {String(automation.condition.expectedValue??'')}</div>:null}
export function AutomationLimitationsCard({automation}:{automation:AssistantAutomation}){return <div className="mt-2 rounded border border-amber-200 bg-amber-50 p-2 text-[11px] text-amber-800">{automation.limitations.map(x=><div key={x}>• {x}</div>)}</div>}
export function AutomationPreviewCard({automation,onConfirm,onCancel,busy}:{automation:AssistantAutomation;onConfirm:()=>void;onCancel:()=>void;busy:boolean}){return <div className="rounded-xl border border-indigo-200 p-3 text-xs"><div className="flex justify-between"><b>Criar automação</b><AutomationStatusBadge status={automation.status}/></div><div className="mt-2 text-sm font-semibold">{automation.title}</div><AutomationScheduleCard automation={automation}/><AutomationConditionCard automation={automation}/><div className="mt-2"><b>Entrega:</b> resultado interno/manual · <b>Persistência:</b> memória</div><AutomationLimitationsCard automation={automation}/><div className="mt-3 flex gap-2"><button disabled={busy} className="rounded bg-indigo-600 px-3 py-2 text-white" onClick={onConfirm}>Confirmar automação</button><button disabled={busy} className="rounded border px-3 py-2" onClick={onCancel}>Cancelar</button></div></div>}
export const AutomationDraftCard=AutomationPreviewCard;
export function AutomationConfirmationCard({children}:{children:ReactNode}){return <div className="rounded border p-2">{children}</div>}
export function AutomationExecutionResultCard({execution}:{execution:AssistantAutomationExecution}){return <div className="mt-2 rounded border p-2 text-xs"><b>{execution.trigger==='test'?'Execução de teste':'Resultado da execução'}</b><div>{execution.resultSummary}</div>{execution.results?.map((r,i)=><div key={`${r.title}-${i}`} className="mt-2 rounded bg-slate-50 p-2"><b>{r.title}</b><div>{r.summary}</div></div>)}{!!execution.suppressedCount&&<div className="mt-1 text-slate-500">{execution.suppressedCount} repetição(ões) suprimida(s).</div>}</div>}
export function AutomationExecutionHistoryCard({history}:{history:AssistantAutomationExecution[]}){return history.length?<details className="mt-2 text-xs"><summary>Histórico ({history.length})</summary>{history.map((e,i)=><div key={i}>{new Date(e.startedAt).toLocaleString('pt-BR')} · {e.status} · {e.resultCount||0}</div>)}</details>:null}
export function AutomationBlockedCard({message}:{message:string}){return <div className="rounded border border-red-200 bg-red-50 p-2 text-xs text-red-700">{message}</div>}
export function AutomationDiffCard({before,after}:{before:string;after:string}){return <div className="text-xs"><del>{before}</del> → <ins>{after}</ins></div>}
export function AutomationListCard({items,onPause,onResume,onRun,onDelete,busy}:{items:AssistantAutomation[];onPause:(a:AssistantAutomation)=>void;onResume:(a:AssistantAutomation)=>void;onRun:(a:AssistantAutomation,test?:boolean)=>void;onDelete:(a:AssistantAutomation)=>void;busy:boolean}){return <div className="space-y-2">{items.map(a=><div key={a.automationReference} className="rounded-xl border p-3"><div className="flex justify-between"><b className="text-sm">{a.title}</b><AutomationStatusBadge status={a.status}/></div><AutomationScheduleCard automation={a}/><AutomationConditionCard automation={a}/><AutomationLimitationsCard automation={a}/><div className="mt-2 flex flex-wrap gap-2 text-xs"><button disabled={busy} onClick={()=>a.status==='paused'?onResume(a):onPause(a)}>{a.status==='paused'?'Reativar':'Pausar'}</button><button disabled={busy} onClick={()=>onRun(a)}>Executar agora</button><button disabled={busy} onClick={()=>onRun(a,true)}>Testar</button><button disabled={busy} className="text-red-600" onClick={()=>onDelete(a)}>Excluir</button></div></div>)}</div>}
