import { useCallback, useEffect, useRef, useState } from 'react';
import apiClient from '../../lib/apiClient';
import type { AssistantAssetStaging, AssistantImportSession } from '../../types/assistant';

export function ImportAssetStagingPanel({session}:{session:AssistantImportSession}){
 const [assets,setAssets]=useState<AssistantAssetStaging[]>([]),[rowId,setRowId]=useState(session.rows[0]?.rowId||''),[targetType,setTargetType]=useState<'MEDIA_POINT'|'MEDIA_UNIT'>('MEDIA_POINT'),[targetId,setTargetId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 const refresh=useCallback(async()=>{const {data}=await apiClient.get<AssistantAssetStaging[]>('/assistant/assets/staging',{params:{sessionId:session.sessionId}});setAssets(data)},[session.sessionId]);
 useEffect(()=>{void refresh().catch(()=>setError('Não foi possível recuperar os assets desta sessão.'))},[refresh]);
 const run=async(operation:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await operation();await refresh()}catch{setError('Não foi possível concluir a operação com o asset. Revise os dados e tente novamente.')}finally{setBusy(false)}};
 const upload=()=>run(async()=>{const file=fileRef.current?.files?.[0];if(!file||!rowId||!targetId.trim())throw new Error('missing');const form=new FormData();form.append('file',file);form.append('sessionId',session.sessionId);form.append('rowId',rowId);form.append('targetType',targetType);form.append('targetId',targetId.trim());await apiClient.post('/assistant/assets/stage',form)});
 return <div className="mt-3 rounded-lg border border-slate-200 p-2 text-xs"><b>Fotos do inventário</b><p className="mt-1 text-slate-500">O destino é explícito. Nenhuma foto será definida como principal ou ordenada automaticamente.</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><select value={rowId} onChange={e=>setRowId(e.target.value)} className="rounded border p-1">{session.rows.map(row=><option key={row.rowId} value={row.rowId}>Linha {row.sourceIndex+1}</option>)}</select><select value={targetType} onChange={e=>setTargetType(e.target.value as 'MEDIA_POINT'|'MEDIA_UNIT')} className="rounded border p-1"><option value="MEDIA_POINT">MediaPoint</option><option value="MEDIA_UNIT">MediaUnit</option></select><input value={targetId} onChange={e=>setTargetId(e.target.value)} placeholder="ID explícito do destino" className="rounded border p-1"/><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif" className="rounded border p-1"/></div><button disabled={busy} onClick={()=>void upload()} className="mt-2 rounded bg-indigo-600 px-2 py-1 text-white disabled:opacity-50">{busy?'Processando…':'Enviar para revisão'}</button>{error&&<div className="mt-2 rounded bg-red-50 p-2 text-red-700">{error}</div>}<div className="mt-2 space-y-1">{assets.map(asset=><div key={asset.id} className="flex items-center justify-between rounded bg-slate-50 p-2"><span>{asset.targetType} · {asset.targetId} · {asset.status}</span><span className="flex gap-2">{asset.status==='PENDING'&&<><button disabled={busy} onClick={()=>void run(async()=>{await apiClient.post('/assistant/assets/discard',{id:asset.id})})}>Descartar</button><button disabled={busy} onClick={()=>void run(async()=>{await apiClient.post('/assistant/assets/confirm',{id:asset.id})})} className="text-indigo-600">Confirmar vínculo</button></>}</span></div>)}</div></div>;
}
