// Dashboard usa somente backend real.
// As rotas abaixo são relativas ao módulo /api já resolvido pelo apiClient.
// Portanto, o contrato do frontend deve usar /dashboard/... e nunca /api/dashboard/...

export const DRILLDOWN_PAGE_SIZE = 20;

export const DASHBOARD_BACKEND_ROUTES = {
  overview: '/dashboard/overview',
  funnel: '/dashboard/funnel',
  alerts: '/dashboard/alerts',
  drilldown: '/dashboard/drilldown',
  meta: '/dashboard/meta',
  kpiDefinitions: '/dashboard/kpis/definitions',
  commercialSummary: '/dashboard/commercial/summary',
  stalledProposals: '/dashboard/proposals/stalled',
  sellerRanking: '/dashboard/commercial/sellers/ranking',
  commercialProposalsTimeseries: '/dashboard/commercial/proposals/timeseries',
  commercialHighValueOpen: '/dashboard/commercial/high-value-open',
  revenueTimeseries: '/dashboard/revenue/timeseries',
  cashflowTimeseries: '/dashboard/cashflow/timeseries',
  topClients: '/dashboard/top/clients',
  receivablesAgingSummary: '/dashboard/receivables/aging/summary',
  financialSummary: '/dashboard/finance/summary',
  receivablesComposition: '/dashboard/finance/receivables/composition',
  criticalInvoices: '/dashboard/finance/critical-invoices',
  lateClients: '/dashboard/finance/late-clients',
  largestOpenReceivables: '/dashboard/finance/largest-open-receivables',
  largestExpenses: '/dashboard/finance/largest-expenses',
  clientsSummary: '/dashboard/clients/summary',
  clientsTopCampaigns: '/dashboard/clients/top-campaigns',
  clientsOpenProposals: '/dashboard/clients/open-proposals',
  clientsInactiveRisk: '/dashboard/clients/inactive-risk',
  clientsRegionDistribution: '/dashboard/clients/regions',
  oohOpsSummary: '/dashboard/ooh/ops/summary',
  operationsLateRegions: '/dashboard/operations/regions/late',
  operationsCityStatus: '/dashboard/operations/cities/status',
  doohSummary: '/dashboard/dooh/summary',
  inventorySummary: '/dashboard/inventory/summary',
  inventoryMap: '/dashboard/inventory/map',
  inventoryRegionDistribution: '/dashboard/inventory/distribution/regions',
  inventoryTypeDistribution: '/dashboard/inventory/distribution/types',
  inventorySubtypeDistribution: '/dashboard/inventory/distribution/subcategories',
  inventoryOpportunitySummary: '/dashboard/inventory/opportunities',
  inventoryRanking: '/dashboard/inventory/ranking',
} as const;
